# Site Settings
title: Govern Artificial Intelligence
email: hello@govern-ai.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/governai"
url: "http://sahildeo.github.io"
twitter_username: cpcEU
github_username:  sahildeo
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
theme: minima
